### ISSUE TITLE
Trigger refresh when removing an item

### ISSUE THREAD

**Issue by kingflurkel** [Juicy/juicy-tile-list#24]

**Comment by tomalec** [comment]
I have fixed it in [repackSeparation](https://github.com/Juicy/juicy-tile-list/tree/repackSeparation) branch. As we are not trying to squeeze extreme performance out of it, now all repacks/refreshes will be on demand, and disabled by default. So, to react to adding and removing an item you need to use:
```html
<juicy-tile-list refreshOnMutation>
```

@kingflurkel Sorry, that it took so long, you can now test it if you want, we will release it with next version, once all listeners/observers will work on-demand.

**Comment by kingflurkel** [comment]
Ok, will test this later (we're upgrading to 1.0)

**Comment by tomalec** [comment]
Thanks.

Are you upgrading to juicy-tile-list 1.0, or Polymer 1.0? ;)
