### ISSUE TITLE
Consider changing "virtual containers" into real "Shadow DOM containers"

### ISSUE THREAD

**Issue by tomalec** [Juicy/juicy-tile-list#29]
As we now have tiles in ShadowDOM, we could mess with DOM there.
We would still keep the grail of not touching user's elements, and polluting the (light) DOM.
But we will simplify the component, on both conceptual and code level.

The price is that we may hit the performance as we would perform DOM moves.

However, I think it's worth to measure the impact, as we wouldn't probably do much around the DOM - we will construct the separated tree on load(or setup change), then just distribute child nodes as we do anyways.

**Comment by warpech** [comment]
Could you explain the difference from current soliution? Currently virtual groups are `<div>`s in `juicy-tile-list` Shadow DOM. This `<div>` renders the group backgroun and border, but does not redistribute content.

**Comment by tomalec** [comment]
Exactly. 
So for 
```html
<juicy-tile-list>
	<div>0</div>
	<div>1</div>
	<div>2</div>
</juicy-tile-list>
```
with setup
```javascript
{
	items:[
		{
			id: "group1",
			items:[

				{
					id:0
				},
				{
					id:1
				}
			],
			{
				id:2
			}
		}
	]
}
```

ShadowDOM looks like:
```
<div id="container">
	<div class="juicy-tile" id="0"><content select="[juicy-tile=0]"></content></div>
	<div class="juicy-tile" id="1"><content select="[juicy-tile=1]"></content></div>
	<div class="juicy-tile" id="2"><content select="[juicy-tile=2]"></content></div>
	<div class="containerBackground" id="group1"></div>
</div>
```
But it could:
```html
<div id="container">
	<div class="juicy-tile" id="2"><content select="[juicy-tile=2]"></content></div>
	<div class="containerBackground" id="group1">	
		<div class="juicy-tile" id="0"><content select="[juicy-tile=0]"></content></div>
		<div class="juicy-tile" id="1"><content select="[juicy-tile=1]"></content></div>
	</div>
</div>
```


However it may collide with `.content`(former `.innerHTML` property of group.

**Comment by tomalec** [comment]
ShadowDOM containers are used for `tightGroups` in juicy-tile-grid, in juicy-tile-list, it seems as currently unnecessary overhead, and performance hit.
