### ISSUE TITLE
Rename height-/widthAuto to precalculateHeight precalculateWidth

### ISSUE THREAD

**Issue by tomalec** [Juicy/juicy-tile-list#30]
As this describes precisely what it is and does not lead to the confusion, especially, when re-packing will be disabled for resize event

**Comment by miyconst** [comment]
So, this means that `width: auto;` won't resize tile on the fly? In previous realization a tile with `width: auto` would automatically change it's size according to content inside. It is no longer true, right?

**Comment by tomalec** [comment]
It never did "resize on fly", it have been resizing on repack, and it still does, but right now, the tiles are not "repacked on fly". 

So it is in fact `precalculateHeightOnEveryRepack` flag ;)

**Comment by miyconst** [comment]
What if a tile could grow/shrink in size during application life circle? What styles should be applied?

**Comment by tomalec** [comment]
Here is an issue for that https://github.com/Juicy/juicy-tile-grid/issues/10

**Comment by miyconst** [comment]
Then `heightAuto` & `widthAuto` should be renamed to `precalculateHeight` & `precalculateWidth`. In the UI it will be `precalculate` checkbox. Correct?

**Comment by tomalec** [comment]
Correct
9 lip 2015 10:14 "Konstantin" <notifications@github.com> napisał(a):

**Comment by tomalec** [comment]
Released in [Juicy/juicy-tile-list@0.3.0](https://github.com/Juicy/juicy-tile-list/releases/tag/0.3.0)
