### ISSUE TITLE
Juicy-tile-list does not work with text nodes; what to do about it

### ISSUE THREAD

**Issue by warpech** [Juicy/juicy-tile-list#34]
It happened to me more than once that I was trying to render such template in `juicy-tile-list`:

```
<template>
   Hello World
</template>
```

As an app developer I would totally expect this to work. It doesn't work with `juicy-tile-list`, because only element nodes are rendered. Text nodes are ignored.

This works as expected:

```
<template>
   <div>Hello World</div>
</template>
```

I propose to either:

1. wrap text nodes in Shadow DOM (hard)
2. show `console.error` for any non-empty text node in `juicy-tile-list` root (easy)

**Comment by tomalec** [comment]
1. Iterating over child text nodes should not be that hard. Distribution of content for separated nodes would be a big one, as we cannot select them with CSS selectors. If w3c/webcomponents#60 get solved, we could think about distributing text nodes programmatically.
2. Seems to be the only way to go, as we do not want to wrpa them in light DOM.

**Comment by warpech** [comment]
@miyconst Could you implement point 2.? Expected error message is: 

> juicy-tile-list can only render DOM element nodes. Provided input contains a text node which cannot be rendered. Wrap it in a `<div>` to fix the problem. Problematic text node: "Hello World" (/path/to/html.html)

**Comment by miyconst** [comment]
Okay.

**Comment by tomalec** [comment]
According to [W3C CSS Grid Layout spec](http://www.w3.org/TR/css-grid-1/#grid-items):
> each child of a grid container becomes a grid item, and each contiguous run of text that is directly contained inside a grid container is wrapped in an anonymous grid item. 
Therefore Extreme Clean Solution would be to wrap it into a tile. 

But probably we should wait for Imperative distribution API

**Comment by warpech** [comment]
Still not doable in `position: absolute` or Flexbox, so very far from working in a fallback.

**Comment by tomalec** [comment]
Why it's not? I believe wrapping doability does not depend on CSS Grid, but on ShadowDOM.

**Comment by warpech** [comment]
Ok, agreed, but in CSS Grid it works without Shadow DOM and we want to minimize the need for runtime processing.

**Comment by tomalec** [comment]
Native functionality will not fit our needs, as we will have no element to apply layout setup to.
