### ISSUE TITLE
Polymer 1.0?

### ISSUE THREAD

**Issue by wintersandroid** [Juicy/juicy-tile-list#35]
Now polymer 1.0 is out, it would be nice to have a compatible version of this..

**Comment by tomalec** [comment]
Thanks for feedback @wintersandroid We definitely plan to do so.

Unfortunately, we use some features that were deprecated (or at leas deprecated for first release of Polymer), or removed from polyfill, like inheritance, and sophisticated Shadow DOM use. So it's hard to promise any precise date.

We'll try to do is as soon as we can, as most of our projects are based on Polymer.

Any comments, PRs, or ideas are more than welcome :)

**Comment by tomalec** [comment]
It's now vanilla Custom Element, so it works with any version of Polymer. Tested with 1.2
