### ISSUE TITLE
Support right-to-left and other orientations

### ISSUE THREAD

**Issue by tomalec** [Juicy/juicy-tile-list#38]
Currently we do support following directions of packing
 - "rightDown" - find place on right, if none go down /
  horizontal layers left-to-right
 - "downRight" - find place bellow, if none go right /
  horizontal layers left-to-right 

It would be nice to support at least left-to-right direction: for RTL languages, though layouts, for compatibility with bootstrap/flexbox/flexgrid demos (Juicy/juicy-tile-grid#13) ;)
Bottom up seems awkward, but why don't we support it as well.

**Comment by tomalec** [comment]
After brief investigation it seems, that even if we could add new sorters might be cool, and gives opportunity to provide very weird orders. It only chooses slot to pack, and then place a rectangle in  same `x,y` as slot, so conceptually in top left corner.

Then I think it makes no point of changing packing algorithm, as from it's point of view positions, angle, direction, and interpretation of X  & Y axes does not matter, and we should not mess the code and increase performance costs.

The think we would like to achieve is completely visual issue, so we can rotate, mirror, flip the axes as we would like.

Therefore I would 
- [x] 1. leave current "downRight" and "rightDown" sorters separated in `Packer` as they are, as choosing between them is cheap, however I would rename them to 
 1. `"horizontal", "vertical"`,
 2. `"xTy", "yTx"`, or
 3. `"x_then_y","y_then_x"` (`Package`, and `Rectangle` uses only abstract `x,y`

- [ ] 2. implement additional property:
  1. flag `"leftToRight": true`,
  2. string property `"horizontalDirection": "RTL"||"LTR"`
- [ ] 3. implement additional property:
  1. flag `"bottomUp": true`,
  2. string property `"verticalDirection": "BU"||"UTB"`


WDYT @miyconst? Any opinion on name to choose?

**Comment by tomalec** [comment]
I've added experimental support for `.leftToRight` and `.bottomUp` to the gh-pages branch

**Comment by miyconst** [comment]
I like the first variant of all points.

1. `"direction": String ("horizontal", "vertical")`.
2. `"leftToRight": Boolean`.
3. `"bottomToTop": Boolean`.

**Comment by tomalec** [comment]
With `"horizontal", "vertical"` the question is which is which ;), 

I would say, that current default is `"horizontal"` as it lays horizontal layers, and grow in horizontal direction first.

**Comment by miyconst** [comment]
Agree.

**Comment by miyconst** [comment]
A bug found:

This is how page looks with `"rightToLeft": false`:
![left-to-right](https://cloud.githubusercontent.com/assets/6435556/8783857/2973003a-2f27-11e5-831d-97a19f17ebc6.png)

And this is how the same page and setup looks with `"rightToLeft": true`:
![right-to-left](https://cloud.githubusercontent.com/assets/6435556/8783874/46d35efe-2f27-11e5-9d67-6a070d59d4da.png)

**Comment by tomalec** [comment]
It seems to be a bug in juicy-tile-grid only, so I created an issue there https://github.com/Juicy/juicy-tile-grid/issues/14
