### ISSUE TITLE
Migrate to vanilla WebComponent

### ISSUE THREAD

**Issue by miyconst** [Juicy/juicy-tile-list#43]
Right now `juicy-tile-list` is a Polymer 0.5 WebComponent. It should be migrated to pure vanilla WebComponent to work with both Polymer 0.5 and Polymer 1.1.

Umbrella issue: https://github.com/Starcounter/Starcounter/issues/2854

**Comment by miyconst** [comment]
@tomalec I have created a new vanilla branch: https://github.com/Juicy/juicy-tile-list/tree/vanilla, take a brief look please.

Now `juicy-tile-list` works without Polymer and all of the tests pass, except those which fail before.

**Comment by tomalec** [comment]
I have posted some comments on https://github.com/Juicy/juicy-tile-list/commit/503198c23ecf6f5dfcb7c82e57824816828b8a1b

**Comment by miyconst** [comment]
Updated all of the examples and tests to don't use Polymer.
