### ISSUE TITLE
Refresh listeners are being attached twice

### ISSUE THREAD

**Issue by tomalec** [Juicy/juicy-tile-list#46]
It seems that changes made to migrate to Vanilla JS https://github.com/Juicy/juicy-tile-list/blame/gh-pages/src/juicy-tile-list.html#L411
caused `addResizeListeners` being executed twice, I susspect that may be a reason why 
https://github.com/Juicy/juicy-tile-list/blob/gh-pages/test/refresh/onResize.html#L87
fails.

@miyconst Could you take a look, at it, and other attributes that are processed by lines 411-415

**Comment by miyconst** [comment]
@tomalec I have removed two redundant code blocks, but it does not fix the tests.

Adding 

```html
<link rel="import" href="../../../../test-fixture/test-fixture.html" />
<script src="../../../../test-fixture/test-fixture-mocha.js"></script>
```

or removing the `<test-fixture>` element fixed `fixture not defined` error, but not the actual fails.

Then sinon seems to spy on original `refresh` method which then replaced:

https://github.com/Juicy/juicy-tile-list/blob/gh-pages/src/juicy-tile-list.html#L382

```js
this.refresh = this.refresh.bind(this);
```

Some of the failing tests don't make sense for me, and some pass when spying on correct `refresh` method.

**Comment by tomalec** [comment]
> I have removed two redundant code blocks, but it does not fix the tests.

I would say we need to remove the previous one, to make sure we attach Listeners after initial Package call.

> Adding ...
or removing the <test-fixture> element fixed fixture not defined error, but not the actual fails.

Are you sure, you use latest web-components-tester?

> Then sinon seems to spy on original refresh method which then replaced:

Good catch, I'll fix that

**Comment by miyconst** [comment]
>I would say we need to remove the previous one, to make sure we attach Listeners after initial Package call.

Moved `attributeChangedCallback` calls under `this.createItemsList();`. Should be fine, right?

**Comment by tomalec** [comment]
I know that it's not used anywhere, but just for future maintenance, you are providing wrong `oldValue` to `attributeChanged`, I would say you should provide `this.refreshOnAttached` instead of true, etc.

**Comment by miyconst** [comment]
Also fixed.
