### ISSUE TITLE
Make tests pass in Edge

### ISSUE THREAD

**Issue by tomalec** [Juicy/juicy-tile-list#48]
It seems that everything works, but for some reason tests fail on Win 10 Edge.

I bet it's similar issues to the ones I have fixed for Firefox and IE recently: Web Components shims make every thing asynchronous.

I tried to test it on virtual machine, but there most of them pass, so maybe it's a matter of increasing the timeout.

@miyconst, if you will have some spare time could you take a look at it?

**Comment by miyconst** [comment]
Okay, I assign it on myself, but won't be able to take it this week for sure.

**Comment by tomalec** [comment]
Thanks. Sure no hurry

**Comment by miyconst** [comment]
@tomalec do you have Edge now? I am very busy these days, no time for this issue :(.

**Comment by tomalec** [comment]
Not yet, I'll upgrade to win 10 this month

**Comment by miyconst** [comment]
@tomalec I tried to figure out what is the reason for the failing test, but was not able. Can you take this issue over, please?

**Comment by tomalec** [comment]
Sure, I'll take it once I'll finish investigation of HTML Imports issue with web-components-tester
