### ISSUE TITLE
Documentation on dynamically adding elements?

### ISSUE THREAD

**Issue by ZepAviator** [Juicy/juicy-tile-list#50]
I have a mixture of images and probably sized DIV elements that I'd like to dynamically create. But when I try to appendChild(element) to the juicy-tile-list, I don't see any results. 

Is there a different way to add elements? Looking for some documentation on this.

**Comment by tomalec** [comment]
Maybe you missed [`refreshOnMutation` attribute](https://github.com/Juicy/juicy-tile-list#options), it will make list refresh when a mutation occurs.
```
<juicy-tile-list refreshOnMutation></juicy-tile-list>
```

If it still does not give you the result you want , please let me know. I'll try to respond sooner than this time.
